### PR TITLE
fix simulator work fail

### PR DESCRIPTION
**Pull request by xkser**
The iOS8-Simulator-Sample  target doesn't work.Then Fix it

### CODE REVIEW

**Comment by shu223** [comment]
I found that it can be built for simulators even including Metal codes for now. So I removed the target and build scheme for simulators. Anyway thanks!!

**Comment by xkser** [comment]
Sorry I cann't run the iOS8Sample scheme even I delete the DeriverData.
Then I delete all the documents and clone the repo again.  the error is Metal

**Comment by shu223** [comment]
What version are you using? I tried Xcode 7.1, and simulator for iOS 8.4 and 9.1.

**Comment by xkser** [comment]
Xcode6.4 iOS 8.4  I doesn't update the Xcode

**Pull request closed without merging**
